# Generated by Django 3.1.2 on 2020-11-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201108_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imggal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtitle', models.CharField(max_length=100)),
                ('imgdesc', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
